# Discord Intents and their associated events
# Reference: https://discord.com/developers/docs/events/gateway#gateway-intents

class_name DiscordIntents
extends Resource

const GUILDS: int = 1 << 0
  #- GUILD_CREATE
  #- GUILD_UPDATE
  #- GUILD_DELETE
  #- GUILD_ROLE_CREATE
  #- GUILD_ROLE_UPDATE
  #- GUILD_ROLE_DELETE
  #- CHANNEL_CREATE
  #- CHANNEL_UPDATE
  #- CHANNEL_DELETE
  #- CHANNEL_PINS_UPDATE
  #- THREAD_CREATE
  #- THREAD_UPDATE
  #- THREAD_DELETE
  #- THREAD_LIST_SYNC
  #- THREAD_MEMBER_UPDATE
  #- THREAD_MEMBERS_UPDATE *
  #- STAGE_INSTANCE_CREATE
  #- STAGE_INSTANCE_UPDATE
  #- STAGE_INSTANCE_DELETE

const GUILD_MEMBERS: int = 1 << 1
  #- GUILD_MEMBER_ADD
  #- GUILD_MEMBER_UPDATE
  #- GUILD_MEMBER_REMOVE
  #- THREAD_MEMBERS_UPDATE *

const GUILD_MODERATION: int = 1 << 2
  #- GUILD_AUDIT_LOG_ENTRY_CREATE
  #- GUILD_BAN_ADD
  #- GUILD_BAN_REMOVE

const GUILD_EXPRESSIONS: int = 1 << 3
  #- GUILD_EMOJIS_UPDATE
  #- GUILD_STICKERS_UPDATE
  #- GUILD_SOUNDBOARD_SOUND_CREATE
  #- GUILD_SOUNDBOARD_SOUND_UPDATE
  #- GUILD_SOUNDBOARD_SOUND_DELETE
  #- GUILD_SOUNDBOARD_SOUNDS_UPDATE

const GUILD_INTEGRATIONS: int = 1 << 4
  #- GUILD_INTEGRATIONS_UPDATE
  #- INTEGRATION_CREATE
  #- INTEGRATION_UPDATE
  #- INTEGRATION_DELETE

const GUILD_WEBHOOKS: int = 1 << 5
  #- WEBHOOKS_UPDATE

const GUILD_INVITES: int = 1 << 6
  #- INVITE_CREATE
  #- INVITE_DELETE

const GUILD_VOICE_STATES: int = 1 << 7
  #- VOICE_CHANNEL_EFFECT_SEND
  #- VOICE_STATE_UPDATE

const GUILD_PRESENCES: int = 1 << 8
  #- PRESENCE_UPDATE

const GUILD_MESSAGES: int = 1 << 9
  #- MESSAGE_CREATE
  #- MESSAGE_UPDATE
  #- MESSAGE_DELETE
  #- MESSAGE_DELETE_BULK

const GUILD_MESSAGE_REACTIONS: int = 1 << 10
  #- MESSAGE_REACTION_ADD
  #- MESSAGE_REACTION_REMOVE
  #- MESSAGE_REACTION_REMOVE_ALL
  #- MESSAGE_REACTION_REMOVE_EMOJI

const GUILD_MESSAGE_TYPING: int = 1 << 11
  #- TYPING_START

const DIRECT_MESSAGES: int = 1 << 12
  #- MESSAGE_CREATE
  #- MESSAGE_UPDATE
  #- MESSAGE_DELETE
  #- CHANNEL_PINS_UPDATE

const DIRECT_MESSAGE_REACTIONS: int = 1 << 13
  #- MESSAGE_REACTION_ADD
  #- MESSAGE_REACTION_REMOVE
  #- MESSAGE_REACTION_REMOVE_ALL
  #- MESSAGE_REACTION_REMOVE_EMOJI

const DIRECT_MESSAGE_TYPING: int = 1 << 14
  #- TYPING_START

const MESSAGE_CONTENT: int = 1 << 15

const GUILD_SCHEDULED_EVENTS: int = 1 << 16
  #- GUILD_SCHEDULED_EVENT_CREATE
  #- GUILD_SCHEDULED_EVENT_UPDATE
  #- GUILD_SCHEDULED_EVENT_DELETE
  #- GUILD_SCHEDULED_EVENT_USER_ADD
  #- GUILD_SCHEDULED_EVENT_USER_REMOVE

const AUTO_MODERATION_CONFIGURATION: int = 1 << 20
  #- AUTO_MODERATION_RULE_CREATE
  #- AUTO_MODERATION_RULE_UPDATE
  #- AUTO_MODERATION_RULE_DELETE

const AUTO_MODERATION_EXECUTION: int = 1 << 21
  #- AUTO_MODERATION_ACTION_EXECUTION

const GUILD_MESSAGE_POLLS: int = 1 << 24
  #- MESSAGE_POLL_VOTE_ADD
  #- MESSAGE_POLL_VOTE_REMOVE

const DIRECT_MESSAGE_POLLS: int = 1 << 25
  #- MESSAGE_POLL_VOTE_ADD
  #- MESSAGE_POLL_VOTE_REMOVE

const DEFAULT: int = GUILDS | GUILD_MESSAGES
const ALL_MESSAGES_TYPING: int = DEFAULT | DIRECT_MESSAGES | DIRECT_MESSAGE_TYPING | GUILD_MESSAGE_TYPING
